### Exercise 7 - Association Rules

First name: Brian
<br>
Last name: Schweigler
<br>
Matriculation number: 16-102-071

#### (1) Take the titanic dataset and using all attributes to predict the class `Survived' (convert age and fare into classes ; exclude names from the attribute list)


#### (a) Choose Three classifiers and evaluate their performance using all attributes;


We will use the same classifiers as in last series, Decision Tree, KNN, Naive Bayes

In [18]:
%load_ext autoreload
%autoreload 2
%matplotlib inline

import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn import preprocessing
from mlxtend.evaluate import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, precision_score, recall_score, f1_score
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import RFE, SelectKBest, f_classif
from sklearn import svm

df = pd.read_csv("data/restaurant.csv")
pd.set_option('display.max_colwidth', None)
le = preprocessing.LabelEncoder()
x_train = df[["choice", "bar", "day", "hungry", "patron", "price", "rain", "booking", "type"]]
x_train = pd.DataFrame(columns=x_train.columns, data=le.fit_transform(x_train.values.flatten()).reshape(x_train.shape))
x_train["time"] = df["time"]

y = le.fit(df["wait"])
y = le.transform(df["wait"])

Xd_train, Xd_test, y_train, y_test = train_test_split(x_train, y, test_size=0.4)

print(Xd_train)
print("y_train = ", y_train, "\n")

print(Xd_test)
print("y_test = ", y_test)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
    choice  bar  day  hungry  patron  price  rain  booking  type  time
8        3    4    4       3       6      0     4        3    10    60
9        4    4    4       4       6      2     3        4     7    20
7        3    3    3       4       9      1     4        4    11     0
11       4    4    4       4       6      0     3        3    10    40
2        4    4    3       3       9      0     3        3    10     0
3        4    3    4       4       6      0     3        3    11    20
4        4    3    4       3       6      2     3        4     5    60
y_train =  [0 0 1 1 1 1 0] 

    choice  bar  day  hungry  patron  price  rain  booking  type  time
0        4    3    3       4       9      2     3        4     5     0
6        3    4    3       3       8      0     4        3    10    20
10       3    3    3       3       8      0     3        3    11     0
1        4    3    3       4   

In [26]:
# Create a svm classifier using one kernel (linear, polynomial, and radial basis)
clf = svm.SVC(kernel='linear')
clf.fit(Xd_train, y_train)

y_pred = clf.predict(Xd_test)
NB_Accuracy = accuracy_score(y_test, y_pred)

print("y_test with linear kernel = ", y_test)
print("y_pred with linear kernel = ", y_pred, "\n")
print("NB_Accuracy with linear kernel = ", NB_Accuracy, "\n")
print("Confusion Matrix with linear kernel \n", confusion_matrix(y_test, y_pred))

y_test with linear kernel =  [1 0 0 0 1]
y_pred with linear kernel =  [0 1 1 1 1] 

NB_Accuracy with linear kernel =  0.2 

Confusion Matrix with linear kernel 
 [[0 3]
 [1 1]]


In [27]:
clf = svm.SVC(kernel='rbf')
clf.fit(Xd_train, y_train)

y_pred = clf.predict(Xd_test)
NB_Accuracy = accuracy_score(y_test, y_pred)

print("y_test with rbf kernel = ", y_test)
print("y_pred with rbf kernel  = ", y_pred, "\n")
print("NB_Accuracy with rbf kernel  = ", NB_Accuracy, "\n")
print("Confusion Matrix with rbf kernel \n", confusion_matrix(y_test, y_pred))

y_test with rbf kernel =  [1 0 0 0 1]
y_pred with rbf kernel  =  [1 1 1 1 1] 

NB_Accuracy with rbf kernel  =  0.4 

Confusion Matrix with rbf kernel 
 [[0 3]
 [0 2]]


In [28]:
clf = svm.SVC(kernel='poly')
clf.fit(Xd_train, y_train)

y_pred = clf.predict(Xd_test)
NB_Accuracy = accuracy_score(y_test, y_pred)

print("y_test with poly kernel = ", y_test)
print("y_pred with poly kernel = ", y_pred, "\n")
print("NB_Accuracy with poly kernel = ", NB_Accuracy, "\n")
print("Confusion Matrix with poly kernel \n", confusion_matrix(y_test, y_pred))

y_test with poly kernel =  [1 0 0 0 1]
y_pred with poly kernel =  [1 1 1 1 1] 

NB_Accuracy with poly kernel =  0.4 

Confusion Matrix with poly kernel 
 [[0 3]
 [0 2]]
