### Exercise 7 - Association Rules

First name: Brian
<br>
Last name: Schweigler
<br>
Matriculation number: 16-102-071

#### (1) Problem: Decide whether to wait for a table at a restaurant, based on various attributes.


We will use the same classifiers as in last series, Decision Tree, KNN, Naive Bayes

In [31]:
%load_ext autoreload
%autoreload 2
%matplotlib inline

import pandas as pd
import numpy as np
from sklearn.tree import DecisionTreeClassifier
from sklearn import preprocessing
from mlxtend.evaluate import accuracy_score
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix, precision_score, recall_score, f1_score
from sklearn.model_selection import train_test_split
from sklearn.feature_selection import RFE, SelectKBest, f_classif
from sklearn import svm
from mlxtend.frequent_patterns import apriori, association_rules

df = pd.read_csv("data/restaurant.csv")
pd.set_option('display.max_colwidth', None)
le = preprocessing.LabelEncoder()
x_train = df[["choice", "bar", "day", "hungry", "patron", "price", "rain", "booking", "type"]]
x_train = pd.DataFrame(columns=x_train.columns, data=le.fit_transform(x_train.values.flatten()).reshape(x_train.shape))
x_train["time"] = df["time"]

y = le.fit(df["wait"])
y = le.transform(df["wait"])

Xd_train, Xd_test, y_train, y_test = train_test_split(x_train, y, test_size=0.4)

print(Xd_train)
print("y_train = ", y_train, "\n")

print(Xd_test)
print("y_test = ", y_test)

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload
    choice  bar  day  hungry  patron  price  rain  booking  type  time
2        4    4    3       3       9      0     3        3    10     0
10       3    3    3       3       8      0     3        3    11     0
9        4    4    4       4       6      2     3        4     7    20
5        3    4    3       4       9      1     4        3     7     0
3        4    3    4       4       6      0     3        3    11    20
8        3    4    4       3       6      0     4        3    10    60
11       4    4    4       4       6      0     3        3    10    40
y_train =  [1 0 0 1 1 0 1] 

   choice  bar  day  hungry  patron  price  rain  booking  type  time
7       3    3    3       4       9      1     4        4    11     0
6       3    4    3       3       8      0     4        3    10    20
4       4    3    4       3       6      2     3        4     5    60
0       4    3    3       4       9

In [26]:
# Create a svm classifier using one kernel (linear, polynomial, and radial basis)
clf = svm.SVC(kernel='linear')
clf.fit(Xd_train, y_train)

y_pred = clf.predict(Xd_test)
NB_Accuracy = accuracy_score(y_test, y_pred)

print("y_test with linear kernel = ", y_test)
print("y_pred with linear kernel = ", y_pred, "\n")
print("NB_Accuracy with linear kernel = ", NB_Accuracy, "\n")
print("Confusion Matrix with linear kernel \n", confusion_matrix(y_test, y_pred))

y_test with linear kernel =  [1 0 0 0 1]
y_pred with linear kernel =  [0 1 1 1 1] 

NB_Accuracy with linear kernel =  0.2 

Confusion Matrix with linear kernel 
 [[0 3]
 [1 1]]


In [27]:
clf = svm.SVC(kernel='rbf')
clf.fit(Xd_train, y_train)

y_pred = clf.predict(Xd_test)
NB_Accuracy = accuracy_score(y_test, y_pred)

print("y_test with rbf kernel = ", y_test)
print("y_pred with rbf kernel  = ", y_pred, "\n")
print("NB_Accuracy with rbf kernel  = ", NB_Accuracy, "\n")
print("Confusion Matrix with rbf kernel \n", confusion_matrix(y_test, y_pred))

y_test with rbf kernel =  [1 0 0 0 1]
y_pred with rbf kernel  =  [1 1 1 1 1] 

NB_Accuracy with rbf kernel  =  0.4 

Confusion Matrix with rbf kernel 
 [[0 3]
 [0 2]]


In [28]:
clf = svm.SVC(kernel='poly')
clf.fit(Xd_train, y_train)

y_pred = clf.predict(Xd_test)
NB_Accuracy = accuracy_score(y_test, y_pred)

print("y_test with poly kernel = ", y_test)
print("y_pred with poly kernel = ", y_pred, "\n")
print("NB_Accuracy with poly kernel = ", NB_Accuracy, "\n")
print("Confusion Matrix with poly kernel \n", confusion_matrix(y_test, y_pred))

y_test with poly kernel =  [1 0 0 0 1]
y_pred with poly kernel =  [1 1 1 1 1] 

NB_Accuracy with poly kernel =  0.4 

Confusion Matrix with poly kernel 
 [[0 3]
 [0 2]]


#### Co-occurence matrix

In [93]:
cooc_mat = x_train.T.dot(x_train)
cooc_mat

choice  bar  day  hungry  patron  price  rain  booking  type   time
choice      157  150  148     155     312     30   141      144   383    960
bar         150  150  144     150     308     27   141      139   378    920
day         148  144  143     147     294     28   136      137   367    980
hungry      155  150  147     157     315     30   143      144   386    900
patron      312  308  294     315     668     60   296      294   789   1600
price        30   27   28      30      60     14    26       31    52    160
rain        141  141  136     143     296     26   136      133   362    860
booking     144  139  137     144     294     31   133      136   352    860
type        383  378  367     386     789     52   362      352  1032   2300
time        960  920  980     900    1600    160   860      860  2300  11600

#### Calculate support, confidence, completeness, lift, and leverage for the following rules. Build the co-occurrence matrix. (again?)

In [76]:
from mlxtend.preprocessing import TransactionEncoder
from mlxtend.frequent_patterns import apriori, fpmax, fpgrowth

te = TransactionEncoder()
te_ary = te.fit(x_train).transform(x_train)
df_new = pd.DataFrame(te_ary, columns=te.columns_)

frequent_itemsets = fpgrowth(df_new, min_support=0.001, use_colnames=True)
frequent_itemsets

support      itemsets
0    0.416667           (i)
1    0.333333           (e)
2    0.250000           (o)
3    0.166667           (h)
4    0.166667           (c)
..        ...           ...
256  0.083333        (i, m)
257  0.083333     (e, t, m)
258  0.083333     (t, i, m)
259  0.083333     (e, i, m)
260  0.083333  (e, t, i, m)

[261 rows x 2 columns]

In [77]:
association_rules(frequent_itemsets, metric="confidence", min_threshold=0.001)

antecedents consequents  antecedent support  consequent support  \
0            (i)         (r)            0.416667            0.416667   
1            (r)         (i)            0.416667            0.416667   
2            (e)         (i)            0.333333            0.416667   
3            (i)         (e)            0.416667            0.333333   
4            (e)         (r)            0.333333            0.416667   
...          ...         ...                 ...                 ...   
2287      (i, m)      (e, t)            0.083333            0.166667   
2288         (e)   (t, i, m)            0.333333            0.083333   
2289         (t)   (e, i, m)            0.250000            0.083333   
2290         (i)   (e, m, t)            0.416667            0.083333   
2291         (m)   (e, i, t)            0.083333            0.083333   

       support  confidence   lift  leverage  conviction  
0     0.166667    0.400000   0.96 -0.006944    0.972222  
1     0.166667    0.400000   0.96 -0.006944    0.972222  
2     0.250000    0.750000   1.80  0.111111    2.333333  
3     0.250000    0.600000   1.80  0.111111    1.666667  
4     0.083333    0.250000   0.60 -0.055556    0.777778  
...        ...         ...    ...       ...         ...  
2287  0.083333    1.000000   6.00  0.069444         inf  
2288  0.083333    0.250000   3.00  0.055556    1.222222  
2289  0.083333    0.333333   4.00  0.062500    1.375000  
2290  0.083333    0.200000   2.40  0.048611    1.145833  
2291  0.083333    1.000000  12.00  0.076389         inf  

[2292 rows x 9 columns]

As I did not manage to enter the rules specficially, I decided to just have the min_support and min_threshold values as low as possible, to essentially just include all rules possible.

This is bound to include the 10 rules mentioned.


#### Explain these measures

Support: The fraction of the total number of data entries in which the variable occurs.

Confidence: The conditional probability of occurrence of consequent given the antecedent.

Completeness: The ratio the overall transactions where the predicted item appear that is covered by the rule.

Lift: Controls for the support (frequency) of consequent while calculating the conditional probability of occurrence of Y given X.

Leverage: Leverage measures the difference of XX and YY appearing together in the data set and what would be expected if XX and YY were statistically dependent.

#### Use the Apriori algorithm to find frequent item sets. We are only interested in item sets having a support value of at least 50%.

In [80]:
# Inspiration: https://www.kaggle.com/code/sangwookchn/association-rule-learning-with-scikit-learn
from apyori import apriori
rules = apriori(x_train[['choice', 'bar', 'day', 'hungry', 'patron', 'rain', 'booking', 'type']], min_support = 0.5, min_confidence = 0.01)
results = list(rules)
results = pd.DataFrame(results)
results.head(5)

items  support     ordered_statistics
0   (a)      0.5  [((), (a), 0.5, 1.0)]
1   (n)      0.5  [((), (n), 0.5, 1.0)]
2   (r)      0.5  [((), (r), 0.5, 1.0)]

Alternative variant, where support is at max 0.25 for some reason:

In [92]:
rules = association_rules(frequent_itemsets, metric="support", min_threshold=0.25)
rules

antecedents consequents  antecedent support  consequent support  support  \
0         (e)         (i)            0.333333            0.416667     0.25   
1         (i)         (e)            0.416667            0.333333     0.25   
2         (a)         (r)            0.333333            0.416667     0.25   
3         (r)         (a)            0.416667            0.333333     0.25   
4         (r)         (n)            0.416667            0.333333     0.25   
5         (n)         (r)            0.333333            0.416667     0.25   

   confidence  lift  leverage  conviction  
0        0.75   1.8  0.111111    2.333333  
1        0.60   1.8  0.111111    1.666667  
2        0.75   1.8  0.111111    2.333333  
3        0.60   1.8  0.111111    1.666667  
4        0.60   1.8  0.111111    1.666667  
5        0.75   1.8  0.111111    2.333333